apiVersion: v1
kind: Service
metadata:
  name: vanilla-minecraft-server
  namespace: minecraft
  labels:
    app: vanilla-minecraft-server
spec:
  type: NodePort
  ports:
    - port: 25565
      nodePort: 30565
  selector:
    app: vanilla-minecraft-server
