apiVersion: v1
kind: Namespace
metadata:
  name:  minecraft

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vanilla-minecraft-data-pvc
  namespace: minecraft
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vanilla-minecraft-data
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    # Edit this to be an actual path on your server's filesystem
    path: /mnt/local-volumes/minecraft_vanilla 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dietpi # Edit this to be an actual kubernetes name of your server

---

# docker run -d -it -v /path/on/host:/data -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla-minecraft-server
  namespace: minecraft
  labels:
    app: vanilla-minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanilla-minecraft-server
  template:
    metadata:
      labels:
        app: vanilla-minecraft-server
    spec:
      volumes:
      - name: vanilla-minecraft-data
        persistentVolumeClaim:
          claimName: vanilla-minecraft-data-pvc
      containers:
      - name: vanilla-minecraft-server
        image: itzg/minecraft-server:latest
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 1.5Gi
        env:
          - name:  EULA
            value: 'TRUE'
          - name: VERSION
            value: 1.16.5
          - name: MODE
            value: survival
          - name: MOTD
            value: Just a generic vanilla world
          - name: OPS
            value: UtmostMoney
          - name: ALLOW_FLIGHT
            value: 'false'
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: vanilla-minecraft-data
            mountPath:  /data
        readinessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: vanilla-minecraft-server
  namespace: minecraft
  labels:
    app: vanilla-minecraft-server
spec:
  type: NodePort
  ports:
    - port: 25565
      nodePort: 30565
  selector:
    app: vanilla-minecraft-server
