kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: old-minecraft-data-pvc
  namespace: minecraft
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
